version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "7070:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - web
    environment:
      - DEFAULT_HOST=medlab-academy.ru

  nginx-proxy-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - web

  web:
    image: nginx:alpine
    container_name: nginx-web
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./php:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    environment:
      - VIRTUAL_HOST=medlab-academy.ru
      - LETSENCRYPT_HOST=medlab-academy.ru
      - LETSENCRYPT_EMAIL=yivan030400@yandex.ru

networks:
  web:
    external: false

volumes:
  certs:
  vhost.d:
  html:
