version: '3.7'

services:
  traefik:
    image: traefik:v2.10 # используем последнюю версию Traefik
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true" # Открывает API-дэшборд
      - "--providers.docker=true" # Включает поддержку Docker
      - "--entrypoints.web.address=:80" # Устанавливает HTTP-входную точку на порту 80
      - "--entrypoints.websecure.address=:443" # Устанавливает HTTPS-входную точку на порту 443
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # Использует TLS-верификацию для получения сертификата
      - "--certificatesresolvers.myresolver.acme.email=ivan030400@mail.ru" # Указываем ваш email для Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" # Путь для хранения сертификатов
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080" # Порт для доступа к API-дэшборду
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # Подключаем Docker сокет
      - "./letsencrypt:/letsencrypt" # Каталог для хранения сертификатов


  php-apache:
    image: medlab-academy:latest
    ports:
      - "7070:80"
    volumes:
      - .:/var/www/html
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`example.com`)" # Укажите ваше доменное имя
      - "traefik.http.routers.web.entrypoints=websecure" # Указываем HTTPS входную точку
      - "traefik.http.routers.web.tls.certresolver=myresolver" # Указываем сертификатор